# Generated by Django 4.2 on 2024-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1)),
                ('maioridade', models.BooleanField(default=False)),
                ('alergia_gluten', models.BooleanField(default=False)),
                ('veganos', models.BooleanField(default=False)),
                ('id_registro', models.CharField(max_length=10)),
            ],
        ),
    ]
