# Generated by Django 5.0.3 on 2024-04-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cliente_id_alter_cliente_id_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productname', models.CharField(max_length=200, verbose_name='Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('quantidade', models.IntegerField()),
                ('alergenico', models.BooleanField(default=False, verbose_name='Alergenico')),
                ('vegano', models.BooleanField(default=False, verbose_name='Vegano')),
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
